"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$(pej&e-2coj&lujq-vi9g21p3ego*)lcyw0te2j5@2m@4*6mq'

# SECURITY WARNING: don't run with debug turned on in production!

#==== PRODUCTION MODE =====
#DEBUG = False
#ALLOWED_HOSTS = ["*"]

#==== DEVELOPMENT MODE =====
DEBUG = True

#if DEBUG is False:
#    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
#else:
#    ALLOWED_HOSTS = []


ALLOWED_HOSTS = ["127.0.0.1", "localhost"] if DEBUG is False else []
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "core",
    "sitemap",
    "authentication",
    "errors",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        #'ENGINE' : "django.db.backends.mysql",
        #"NAME" : "",
        #"USER": "",
        #"PASSWORD": "",
        #"HOST": "",
        #"PORT": "",
    }

}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# ===============================================
#           Developer Configuration
# ===============================================

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "public"),
    os.path.join(BASE_DIR, "static"),
)

#Email Configuration
EMAIL_HOST = ''
EMAIL_PORT = 587
EMAIL_HOST_USER = "someone@example.com" # Sender Email
EMAIL_HOST_PASSWORD = ""
EMAIL_USE_TLS = True
EMAIL_BACKEND = "django.core.backends.smtp.EmailBackend"
DEFAULT_FROM_EMAIL = "Admin <{}>".format(EMAIL_HOST_USER)


#Security Configuration
SECURE_BROWSER_XSS_FILTER = True

#Login URL Configuration
LOGIN_URL = "auth/login"
LOGIN_REDIRECT_URL = ""
LOGOUT_REDIRECT_URL = ""
LOGOUT_REDIRECT_URL = "/"

# Media Directory Configuration
MEDIA_ROOT = ""
MEDIA_URL = ""

# Additional Time configuration
TIME_FORMAT = "P"
